import { createCustomer, updateCustomer, deleteCustomer } from "@/app/actions/clients";
import { db } from "@/lib/db";

export const dynamic = "force-dynamic";

export default async function CustomersPage() {
  const customers = await db.customer.findMany({ where: { active: true }, orderBy: { createdAt: "desc" }, include: { _count: { select: { repairOrders: true, sales: true } } } });
  return <>
    <div className="page-header"><div><h2>Clientes</h2><p>Registro, contacto e historial relacionado.</p></div></div>
    <div className="grid-two">
      <section className="card"><h3>Directorio de clientes</h3><div className="table-wrap"><table><thead><tr><th>Cliente</th><th>Contacto</th><th>Ciudad</th><th>Reparaciones</th><th>Ventas</th><th>Acciones</th></tr></thead><tbody>{customers.map((c) => <tr key={c.id}><td><strong>{c.firstName} {c.lastName}</strong><br/><small className="muted">{c.createdAt.toLocaleDateString("es-MX")}</small></td><td>{c.phone}<br/><small>{c.email || "Sin correo"}</small></td><td>{c.city || "—"}</td><td>{c._count.repairOrders}</td><td>{c._count.sales}</td><td><div className="inline-actions"><details><summary className="btn btn-small btn-secondary">Editar</summary><form action={updateCustomer.bind(null,c.id)} className="form-grid one" style={{minWidth:280,marginTop:12}}><div className="field"><label>Nombre</label><input name="firstName" defaultValue={c.firstName} required/></div><div className="field"><label>Apellidos</label><input name="lastName" defaultValue={c.lastName} required/></div><div className="field"><label>Teléfono</label><input name="phone" defaultValue={c.phone} required/></div><div className="field"><label>Correo</label><input name="email" type="email" defaultValue={c.email || ""}/></div><div className="field"><label>Ciudad</label><input name="city" defaultValue={c.city || ""}/></div><input type="hidden" name="privacyAccepted" value="on"/><button className="btn btn-primary" type="submit">Guardar</button></form></details><form action={deleteCustomer.bind(null,c.id)} method="post" style={{display:"inline"}}><button className="btn btn-small btn-danger" type="submit">Eliminar</button></form></div></td></tr>)}</tbody></table></div></section>
      <section className="card"><h3>Registrar cliente</h3><form action={createCustomer} className="form-grid"><div className="field"><label>Nombre</label><input name="firstName" required/></div><div className="field"><label>Apellidos</label><input name="lastName" required/></div><div className="field"><label>Teléfono</label><input name="phone" required/></div><div className="field"><label>Correo</label><input name="email" type="email"/></div><div className="field full"><label>Ciudad</label><input name="city"/></div><label className="field full" style={{flexDirection:"row",alignItems:"center"}}><input type="checkbox" name="privacyAccepted" required style={{width:"auto"}}/> El cliente aceptó el aviso de privacidad.</label><div className="form-actions field full"><button className="btn btn-primary" type="submit">Guardar cliente</button></div></form></section>
    </div>
  </>;
}
