import { AppLogo } from "@/components/AppLogo";
import ClientRealtime from "@/app/cliente/ClientRealtime";
import { requireClientOrder } from "@/lib/customer-auth";
import { decideEstimate, sendCustomerMessage } from "@/app/actions/repair-details";
import { formatMoney } from "@/lib/money";
import { repairStatusLabels, statusProgress } from "@/lib/repair-state";

export const dynamic="force-dynamic";
export default async function ClientPage(){
  const order=await requireClientOrder();const progress=statusProgress(order.status);
  if(order.status === "DELIVERED") return <main className="client-shell"><div className="client-container"><header className="client-header"><AppLogo/><form action="/api/customer/logout" method="post"><button className="btn btn-secondary">Cerrar</button></form></header><section className="client-card"><span className="eyebrow">CONSTANCIA DE ENTREGA</span><div className="page-header" style={{marginTop:16}}><div><h2>Equipo entregado</h2><p>Orden {order.publicFolio}</p></div><span className="badge success">ENTREGADO</span></div><div className="client-summary"><div><span>Equipo</span><strong>{order.device.brand} {order.device.model}</strong></div><div><span>Fecha de entrega</span><strong>{order.deliveredAt?order.deliveredAt.toLocaleString("es-MX"):"Registrada"}</strong></div><div><span>Total de la orden</span><strong>{formatMoney(order.total.toString())}</strong></div><div><span>Sucursal</span><strong>{order.branch.name}</strong></div></div><div className="alert alert-info" style={{marginTop:18}}>Por seguridad, el chat, evidencias y avances detallados dejaron de estar disponibles después de la entrega. Conserva tu folio para cualquier aclaración o garantía.</div></section></div></main>;
  return <main className="client-shell"><ClientRealtime/><div className="client-container"><header className="client-header"><AppLogo/><form action="/api/customer/logout" method="post"><button className="btn btn-secondary">Cerrar seguimiento</button></form></header><section className="client-card"><span className="eyebrow">SEGUIMIENTO PRIVADO</span><div className="page-header" style={{marginTop:16}}><div><h2>{order.device.brand} {order.device.model}</h2><p>Orden {order.publicFolio}</p></div><span className="badge success">{repairStatusLabels[order.status]}</span></div><div className="progress"><span style={{width:`${progress}%`}}/></div><div className="client-summary"><div><span>Avance</span><strong>{progress}%</strong></div><div><span>Presupuesto total</span><strong>{formatMoney(order.total.toString())}</strong></div><div><span>Anticipo</span><strong>{formatMoney(order.deposit.toString())}</strong></div><div><span>Fecha estimada</span><strong>{order.promisedAt?order.promisedAt.toLocaleDateString("es-MX"):"Por confirmar"}</strong></div></div></section>
  <div className="grid-two"><section className="client-card"><h3>Avances de reparación</h3><div className="timeline">{order.updates.map((u)=><div className="timeline-item" key={u.id}><strong>{repairStatusLabels[u.newStatus]}</strong><span>{u.comment}</span><small>{u.createdAt.toLocaleString("es-MX")}</small></div>)}</div></section><section className="client-card"><h3>Diagnóstico</h3><p>{order.diagnosis||"El diagnóstico todavía está en proceso."}</p><div className="info-row"><span>Técnico asignado</span><strong>{order.technician?.name||"Por asignar"}</strong></div><div className="info-row"><span>Sucursal</span><strong>{order.branch.name}</strong></div></section></div>
  <section className="client-card"><h3>Cotizaciones adicionales</h3>{order.estimates.length?order.estimates.map((e)=><div className={`estimate-card ${e.status==="PENDING"?"pending":""}`} key={e.id}><div className="page-header" style={{marginBottom:8}}><div><strong>Versión {e.version} · {e.title}</strong><p>{e.reason}</p></div><span className="badge">{e.status}</span></div><div className="client-summary"><div><span>Refacciones</span><strong>{formatMoney(e.partsAmount.toString())}</strong></div><div><span>Mano de obra</span><strong>{formatMoney(e.laborAmount.toString())}</strong></div><div><span>Impuestos</span><strong>{formatMoney(e.taxAmount.toString())}</strong></div><div><span>Total adicional</span><strong>{formatMoney(e.totalAmount.toString())}</strong></div></div>{e.status==="PENDING"&&<div className="inline-actions" style={{marginTop:15}}><form action={decideEstimate.bind(null,e.id,"ACCEPTED")}><button className="btn btn-primary">ACEPTO LA REPARACIÓN Y EL CARGO ADICIONAL</button></form><form action={decideEstimate.bind(null,e.id,"REJECTED")}><button className="btn btn-danger">NO ACEPTO LA REPARACIÓN ADICIONAL</button></form></div>}</div>):<div className="empty">No hay cotizaciones adicionales pendientes.</div>}</section>
  <section className="client-card"><h3>Mensajes con recepción y técnico</h3><div className="chat">{order.messages.map((m)=><div className={`chat-message ${m.senderType==="CUSTOMER"?"customer":m.senderType==="SYSTEM"?"system":""}`} key={m.id}>{m.body}<small>{m.senderType==="CUSTOMER"?"Tú":m.senderUser?.name||"Sistema"} · {m.createdAt.toLocaleString("es-MX")}</small></div>)}</div><form action={sendCustomerMessage} className="form-grid one" style={{marginTop:14}}><div className="field"><textarea name="body" maxLength={3000} placeholder="Escribe un mensaje para recepción o el técnico" required/></div><button className="btn btn-primary">Enviar mensaje</button></form></section></div></main>;
}
